import os
import torch
import numpy as np
import matplotlib.pyplot as plt

import dataset

# Device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if not torch.cuda.is_available():
    print("Warning CUDA not Found. Using CPU")

# Hyper-parameters
num_epochs = 8
learning_rate = 1e-3

dataset_root = os.getenv("OASIS_ROOT")
if dataset_root is None:
    print("error: need $OASIS_ROOT to be set to root path of dataset")
    exit(1)

print(f"> Load dataset from {dataset_root}")

trainset, testset = dataset.load_datasets(dataset_root)
train_loader = torch.utils.data.DataLoader(trainset, batch_size=40, shuffle=True)
test_loader = torch.utils.data.DataLoader(testset, batch_size=16, shuffle=False)

# Visualise one image from test set data (code generated by Kimi K2)

# Grab one batch
images, segs = next(iter(test_loader))  # images, segs: (B, C, H, W)
image, seg = images[0], segs[0]

H, W = seg.shape[-2:]

fig, axes = plt.subplots(1, 5, figsize=(15, 3))

# Plot image
axes[0].imshow(image.cpu().numpy().transpose(1, 2, 0), cmap='gray')
axes[0].set_title("Image")
axes[0].axis('off')

# Plot each one-hot channel
for ch in range(4):
    axes[ch+1].imshow(seg[ch].cpu().numpy(), cmap='gray', vmin=0, vmax=1)
    axes[ch+1].set_title(f"Seg ch {ch}")
    axes[ch+1].axis('off')

plt.tight_layout()
plt.show()
