import os
import torch
import numpy as np
import matplotlib.pyplot as plt

import dataset

# Device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if not torch.cuda.is_available():
    print("Warning CUDA not Found. Using CPU")

# Hyper-parameters
num_epochs = 8
learning_rate = 1e-3

dataset_root = os.getenv("OASIS_ROOT")
if dataset_root is None:
    print("error: need $OASIS_ROOT to be set to root path of dataset")
    exit(1)

print(f"> Load dataset from {dataset_root}")

trainset, testset = dataset.load_datasets(dataset_root)
train_loader = torch.utils.data.DataLoader(trainset, batch_size=40, shuffle=True)
test_loader = torch.utils.data.DataLoader(testset, batch_size=16, shuffle=False)

# Visualise one batch of test set data (code generated by Kimi K2)

# Grab one batch
images, segs = next(iter(test_loader))  # images, segs: (B, C, H, W)

B = images.size(0)
cols = 2
rows = (B + cols - 1) // cols

fig, axes = plt.subplots(rows, cols * 2, figsize=(cols * 6, rows * 3))
if rows == 1:
    axes = axes.reshape(1, -1)

for i in range(B):
    img = images[i].cpu().numpy().transpose(1, 2, 0)  # (H, W, C)
    seg = segs[i].cpu().numpy().squeeze()  # (H, W)

    row, base = divmod(i, cols)
    ax_img = axes[row, base * 2]
    ax_seg = axes[row, base * 2 + 1]

    ax_img.imshow(np.clip(img, 0, 1), cmap="gray")
    ax_img.set_title(f"Image {i}")
    ax_img.axis("off")

    ax_seg.imshow(seg, cmap="tab10", vmin=0, vmax=1)
    ax_seg.set_title(f"Seg {i}")
    ax_seg.axis("off")

# Hide unused subplots
for j in range(B, rows * cols):
    row, base = divmod(j, cols)
    axes[row, base * 2].axis("off")
    axes[row, base * 2 + 1].axis("off")

plt.tight_layout()
plt.show()
